FROM mcr.microsoft.com/dotnet/sdk:10.0@sha256:e1fc6e423f543119c406d24e2e687d67c569f18f04a37a8b0005d80ad0dcee80

WORKDIR /app

COPY ["Directory.Build.props", "."]
COPY ["Directory.Packages.props", "."]
COPY [".editorconfig", "."]

COPY ["src/", "src/"]
COPY ["tests/", "tests/"]

RUN dotnet restore tests/LotroKoniecDev.TranslationSystem.Domain.Tests.Unit/LotroKoniecDev.TranslationSystem.Domain.Tests.Unit.csproj && \
    dotnet restore tests/LotroKoniecDev.TranslationSystem.API.Tests.Integration/LotroKoniecDev.TranslationSystem.API.Tests.Integration.csproj && \
    dotnet restore tests/LotroKoniecDev.AuthSystem.API.Tests.Integration/LotroKoniecDev.AuthSystem.API.Tests.Integration.csproj

RUN dotnet build tests/LotroKoniecDev.TranslationSystem.Domain.Tests.Unit/LotroKoniecDev.TranslationSystem.Domain.Tests.Unit.csproj -c Release --no-restore && \
    dotnet build tests/LotroKoniecDev.TranslationSystem.API.Tests.Integration/LotroKoniecDev.TranslationSystem.API.Tests.Integration.csproj -c Release --no-restore && \
    dotnet build tests/LotroKoniecDev.AuthSystem.API.Tests.Integration/LotroKoniecDev.AuthSystem.API.Tests.Integration.csproj -c Release --no-restore

CMD echo "== UNIT TESTS (TRANSLATION DOMAIN) START ==" && \
    dotnet test tests/LotroKoniecDev.TranslationSystem.Domain.Tests.Unit/LotroKoniecDev.TranslationSystem.Domain.Tests.Unit.csproj -c Release --no-build --logger "console;verbosity=minimal" && \
    echo "== UNIT TESTS PASSED ==" && \
    echo "== INTEGRATION TESTS (TRANSLATION) START ==" && \
    dotnet test tests/LotroKoniecDev.TranslationSystem.API.Tests.Integration/LotroKoniecDev.TranslationSystem.API.Tests.Integration.csproj -c Release --no-build --logger "console;verbosity=minimal" && \
    echo "== INTEGRATION TESTS (TRANSLATION) PASSED ==" && \
    echo "== INTEGRATION TESTS (AUTH) START ==" && \
    dotnet test tests/LotroKoniecDev.AuthSystem.API.Tests.Integration/LotroKoniecDev.AuthSystem.API.Tests.Integration.csproj -c Release --no-build --logger "console;verbosity=minimal" && \
    echo "== INTEGRATION TESTS (AUTH) PASSED ==" && \
    echo "== ALL TESTS PASSED =="
