-- QA fixture seed for STAGING — puts a handful of rows into every translation status so the
-- manual-QA tickets that depend on a non-default state are actually executable.
--
-- Why this exists: staging holds ~792k imported rows but almost all of them are Untranslated
-- (measured 2026-08-05: 1 Draft, 21 Approved, 0 NeedsReview). Every QA scenario about approving,
-- invalidation or the "poprzednia wersja angielska" comparison block was therefore impossible to
-- run, and a tester who improvises a substitute row files a false bug (#547).
--
-- Run it (owner only, staging only):
--     psql "$STAGING_TMS_URI" -v ON_ERROR_STOP=1 -f scripts/qa/seed-staging.sql
--
--   STAGING_TMS_URI is the staging TMS database in **psql URI form**
--   (postgres://user:pass@host/db?sslmode=require) — not the Npgsql keyword string from
--   /opt/lotro/.env, which psql cannot parse. Convert it by hand.
--
-- Two things to know before running:
--
--   1. NEVER run this against production. It rewrites translation rows in place.
--
--   2. The precomputed polish.txt artifact is NOT regenerated by SQL. After seeding, perform one
--      approve (or one save on an Approved row) in the UI as admin — the projector rebuilds the
--      whole Approved set on any such action, so a single click reconciles the artifact.
--      Until you do, the Approved counts and the downloaded polish.txt disagree, which looks
--      exactly like a bug to a tester.
--
-- Re-runnable: every seeded row is tagged with the [QA-SEED] marker, and step 1 releases the
-- previous seed before a new one is taken. Rows carrying real translator work are never touched —
-- only rows that are still Untranslated with no Polish text are recruited.
--
-- The seeded Polish text is deliberately marked, so it is recognisable in the exported polish.txt.
-- That is expected, not junk data.

\set ON_ERROR_STOP on

BEGIN;

-- 1. Release the previous seed, so re-running does not accumulate fixture rows.
UPDATE translation."Translations"
SET "Status" = 'Untranslated',
    "TranslatedText" = NULL,
    "PreviousSourceText" = NULL,
    "SubmittedById" = NULL,
    "ApprovedById" = NULL,
    "UpdatedAt" = now()
WHERE "TranslatedText" LIKE '[QA-SEED]%'
   OR "PreviousSourceText" LIKE '[QA-SEED]%';

-- 2. Five Draft rows — editor save, list filter, and the admin approve flow (QA-FE-07 / -08).
WITH picked AS (
    SELECT "Id"
    FROM translation."Translations"
    WHERE "Status" = 'Untranslated'
      AND "TranslatedText" IS NULL
      AND "RemovedInVersion" IS NULL
      -- Placeholder-bearing rows are reserved for the placeholder-guard scenario in step 6; if the
      -- seed recruited them they would no longer be Untranslated and step 6 would report nothing.
      AND "SourceText" NOT LIKE '%<--DO\_NOT\_TOUCH!-->%'
    ORDER BY "FileId", "GossipId"
    LIMIT 5
)
UPDATE translation."Translations" AS t
SET "Status" = 'Draft',
    "TranslatedText" = '[QA-SEED] Robocze tlumaczenie do testow QA',
    "SubmittedById" = (SELECT "Id" FROM translation."Translators" ORDER BY "Id" LIMIT 1),
    "UpdatedAt" = now()
FROM picked
WHERE t."Id" = picked."Id";

-- 3. Five Approved rows — distribution contents, status filter, "approve disappears" (QA-FE-10).
WITH picked AS (
    SELECT "Id"
    FROM translation."Translations"
    WHERE "Status" = 'Untranslated'
      AND "TranslatedText" IS NULL
      AND "RemovedInVersion" IS NULL
      -- Placeholder-bearing rows are reserved for the placeholder-guard scenario in step 6; if the
      -- seed recruited them they would no longer be Untranslated and step 6 would report nothing.
      AND "SourceText" NOT LIKE '%<--DO\_NOT\_TOUCH!-->%'
    ORDER BY "FileId", "GossipId"
    LIMIT 5
)
UPDATE translation."Translations" AS t
SET "Status" = 'Approved',
    "TranslatedText" = '[QA-SEED] Zatwierdzone tlumaczenie do testow QA',
    "SubmittedById" = (SELECT "Id" FROM translation."Translators" ORDER BY "Id" LIMIT 1),
    "ApprovedById" = (SELECT "Id" FROM translation."Translators" ORDER BY "Id" LIMIT 1),
    "UpdatedAt" = now()
FROM picked
WHERE t."Id" = picked."Id";

-- 4. Five NeedsReview (superseded) rows — the invalidation backlog and the side-by-side
--    "Poprzednia wersja angielska (do porownania)" block, which renders only when
--    PreviousSourceText is present (QA-FE-07, the scenario that produced the false positive #547).
WITH picked AS (
    SELECT "Id"
    FROM translation."Translations"
    WHERE "Status" = 'Untranslated'
      AND "TranslatedText" IS NULL
      AND "RemovedInVersion" IS NULL
      -- Placeholder-bearing rows are reserved for the placeholder-guard scenario in step 6; if the
      -- seed recruited them they would no longer be Untranslated and step 6 would report nothing.
      AND "SourceText" NOT LIKE '%<--DO\_NOT\_TOUCH!-->%'
    ORDER BY "FileId", "GossipId"
    LIMIT 5
)
UPDATE translation."Translations" AS t
SET "Status" = 'NeedsReview',
    "TranslatedText" = '[QA-SEED] Tlumaczenie czekajace na ponowny przeglad',
    "PreviousSourceText" = '[QA-SEED] Older English wording — ' || t."SourceText",
    "SubmittedById" = (SELECT "Id" FROM translation."Translators" ORDER BY "Id" LIMIT 1),
    "UpdatedAt" = now()
FROM picked
WHERE t."Id" = picked."Id";

COMMIT;

-- 5. Report the seeded rows. Paste these FileId/GossipId pairs into the QA tickets so the tester
--    opens a known row instead of hunting for one.
\echo ''
\echo '=== Seeded rows (put these ids in the QA tickets) ==='
SELECT "Status", "FileId", "GossipId"
FROM translation."Translations"
WHERE "TranslatedText" LIKE '[QA-SEED]%'
ORDER BY "Status", "FileId", "GossipId";

-- 6. Rows whose English carries a placeholder — for the placeholder-guard scenario (QA-FE-07).
--    Read-only: these stay Untranslated on purpose, the tester types the Polish themselves.
\echo ''
\echo '=== Untranslated rows containing <--DO_NOT_TOUCH!--> (placeholder-guard scenario) ==='
SELECT "FileId", "GossipId"
FROM translation."Translations"
WHERE "Status" = 'Untranslated'
  AND "RemovedInVersion" IS NULL
  AND "SourceText" LIKE '%<--DO\_NOT\_TOUCH!-->%'
ORDER BY "FileId", "GossipId"
LIMIT 3;

\echo ''
\echo 'NEXT STEP: approve one row in the UI as admin to force the artifact rebuild,'
\echo 'otherwise the downloaded polish.txt will not match the Approved set.'
