#!/usr/bin/env bash
# Generates the three production OpenIddict secrets the auth-api requires in Production
# (validated fail-fast at startup — see OpenIddictSettingsValidator):
#   OpenIddict__EncryptionKey__Key            base64 of a 32-byte symmetric key
#   OpenIddict__SigningKey__RsaPrivateKeyXml  base64 of RSA.ToXmlString(true), 2048-bit
#   OpenIddict__ApiClientSecret               >= 32 chars
#
# Prints KEY=VALUE lines on stdout — append them to your git-ignored .env.prod, e.g.:
#   scripts/gen-openiddict-keys.sh >> .env.prod
#
# Requires: openssl + python3 (python3 only converts the RSA key to .NET's XML format,
# using the standard library — no third-party packages).

set -euo pipefail

ENC_KEY="$(openssl rand -base64 32)"
API_SECRET="$(openssl rand -hex 24)"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

openssl genrsa -out "$TMP/key.pem" 2048 >/dev/null 2>&1
# Force PKCS#1 ("RSA PRIVATE KEY") so the DER is a plain SEQUENCE of integers.
openssl rsa -in "$TMP/key.pem" -traditional -out "$TMP/pkcs1.pem" >/dev/null 2>&1

RSA_XML_B64="$(python3 - "$TMP/pkcs1.pem" <<'PY'
import sys, base64, re

pem = open(sys.argv[1]).read()
der = base64.b64decode(re.sub(r"-----[^-]+-----|\s", "", pem))

def read_len(d, i):
    first = d[i]; i += 1
    if first < 0x80:
        return first, i
    count = first & 0x7F
    return int.from_bytes(d[i:i + count], "big"), i + count

i = 0
assert der[i] == 0x30, "expected SEQUENCE"; i += 1
_, i = read_len(der, i)
ints = []
while i < len(der):
    assert der[i] == 0x02, "expected INTEGER"; i += 1
    length, i = read_len(der, i)
    ints.append(int.from_bytes(der[i:i + length], "big")); i += length

# RSAPrivateKey ::= version, modulus(n), publicExponent(e), privateExponent(d),
#                   prime1(p), prime2(q), exponent1(dp), exponent2(dq), coefficient(invq)
_, n, e, d, p, q, dp, dq, invq = ints[:9]
klen = (n.bit_length() + 7) // 8
half = (klen + 1) // 2

def b(value, length):
    return base64.b64encode(value.to_bytes(length, "big")).decode()

xml = (
    "<RSAKeyValue>"
    f"<Modulus>{b(n, klen)}</Modulus>"
    f"<Exponent>{b(e, (e.bit_length() + 7) // 8)}</Exponent>"
    f"<P>{b(p, half)}</P>"
    f"<Q>{b(q, half)}</Q>"
    f"<DP>{b(dp, half)}</DP>"
    f"<DQ>{b(dq, half)}</DQ>"
    f"<InverseQ>{b(invq, half)}</InverseQ>"
    f"<D>{b(d, klen)}</D>"
    "</RSAKeyValue>"
)
print(base64.b64encode(xml.encode()).decode())
PY
)"

echo "# Generated by scripts/gen-openiddict-keys.sh — keep secret, never commit."
echo "OpenIddict__EncryptionKey__Key=$ENC_KEY"
echo "OpenIddict__ApiClientSecret=$API_SECRET"
echo "OpenIddict__SigningKey__RsaPrivateKeyXml=$RSA_XML_B64"
