#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Generates the three production OpenIddict secrets the auth-api requires in Production
    (validated fail-fast at startup — see OpenIddictSettingsValidator).

.DESCRIPTION
    Prints KEY=VALUE lines on stdout — append them to your git-ignored .env.prod, e.g.:
      ./scripts/gen-openiddict-keys.ps1 >> .env.prod
        OpenIddict__EncryptionKey__Key            base64 of a 32-byte symmetric key
        OpenIddict__SigningKey__RsaPrivateKeyXml  base64 of RSA.ToXmlString(true), 2048-bit
        OpenIddict__ApiClientSecret               48-char hex secret
#>

$ErrorActionPreference = 'Stop'

$encBytes = [byte[]]::new(32)
[System.Security.Cryptography.RandomNumberGenerator]::Fill($encBytes)
$encKey = [Convert]::ToBase64String($encBytes)

$secretBytes = [byte[]]::new(24)
[System.Security.Cryptography.RandomNumberGenerator]::Fill($secretBytes)
$apiSecret = ([System.BitConverter]::ToString($secretBytes) -replace '-', '').ToLower()

$rsa = [System.Security.Cryptography.RSA]::Create(2048)
$rsaXmlB64 = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($rsa.ToXmlString($true)))

Write-Output "# Generated by scripts/gen-openiddict-keys.ps1 — keep secret, never commit."
Write-Output "OpenIddict__EncryptionKey__Key=$encKey"
Write-Output "OpenIddict__ApiClientSecret=$apiSecret"
Write-Output "OpenIddict__SigningKey__RsaPrivateKeyXml=$rsaXmlB64"
