// <auto-generated />
using System;
using LotroKoniecDev.TranslationSystem.Persistence.DbContexts.WriteDbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LotroKoniecDev.TranslationSystem.Persistence.Migrations
{
    [DbContext(typeof(ApplicationWriteDbContext))]
    [Migration("20260612214124_RefactorGameVersionToOwnsOne")]
    partial class RefactorGameVersionToOwnsOne
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("translation")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LotroKoniecDev.TranslationSystem.Domain.Aggregates.GameVersionAggregate.Entities.GameVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("GameVersions", "translation");
                });

            modelBuilder.Entity("LotroKoniecDev.TranslationSystem.Domain.Aggregates.GameVersionAggregate.Entities.GameVersion", b =>
                {
                    b.OwnsOne("LotroKoniecDev.TranslationSystem.Domain.Aggregates.GameVersionAggregate.ValueObjects.LotroNotationVersion", "LotroNotationVersion", b1 =>
                        {
                            b1.Property<Guid>("GameVersionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)")
                                .HasColumnName("LotroNotationVersion");

                            b1.HasKey("GameVersionId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("GameVersions", "translation");

                            b1.WithOwner()
                                .HasForeignKey("GameVersionId");
                        });

                    b.Navigation("LotroNotationVersion")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
