// <auto-generated />
using System;
using System.Collections.Generic;
using LotroKoniecDev.TranslationSystem.Persistence.DbContexts.WriteDbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LotroKoniecDev.TranslationSystem.Persistence.Migrations
{
    [DbContext(typeof(ApplicationWriteDbContext))]
    [Migration("20260706032709_AddTranslationConcurrencyToken")]
    partial class AddTranslationConcurrencyToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("translation")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LotroKoniecDev.TranslationSystem.Domain.Aggregates.GameVersionAggregate.Entities.GameVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("GameVersions", "translation");
                });

            modelBuilder.Entity("LotroKoniecDev.TranslationSystem.Domain.Aggregates.TranslationAggregate.Entities.Translation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApprovedById")
                        .HasColumnType("uuid")
                        .HasColumnName("ApprovedById");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IntroducedInVersion")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LastSourceChangeInVersion")
                        .HasColumnType("uuid");

                    b.Property<string>("PreviousSourceText")
                        .HasColumnType("text");

                    b.Property<Guid?>("RemovedInVersion")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("SubmittedById")
                        .HasColumnType("uuid")
                        .HasColumnName("SubmittedById");

                    b.Property<string>("TranslatedText")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("Status")
                        .HasFilter("\"RemovedInVersion\" IS NULL");

                    b.HasIndex("SubmittedById");

                    b.HasIndex("TranslatedText");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("TranslatedText"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("TranslatedText"), new[] { "gin_trgm_ops" });

                    b.ToTable("Translations", "translation");
                });

            modelBuilder.Entity("LotroKoniecDev.TranslationSystem.Domain.Aggregates.TranslatorAggregate.Entities.Translator", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ProvisionedAt")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "DisplayName", "LotroKoniecDev.TranslationSystem.Domain.Aggregates.TranslatorAggregate.Entities.Translator.DisplayName#DisplayName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("DisplayName");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Email", "LotroKoniecDev.TranslationSystem.Domain.Aggregates.TranslatorAggregate.Entities.Translator.Email#Email", b1 =>
                        {
                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)")
                                .HasColumnName("Email");
                        });

                    b.HasKey("Id");

                    b.HasIndex("IdentityId")
                        .IsUnique();

                    b.ToTable("Translators", "translation");
                });

            modelBuilder.Entity("LotroKoniecDev.TranslationSystem.Projections.PrecomputedTranslationFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.HasKey("Id");

                    b.HasIndex("Language")
                        .IsUnique();

                    b.ToTable("TranslationArtifacts", "translation");
                });

            modelBuilder.Entity("LotroKoniecDev.TranslationSystem.Domain.Aggregates.GameVersionAggregate.Entities.GameVersion", b =>
                {
                    b.OwnsOne("LotroKoniecDev.TranslationSystem.Domain.Aggregates.GameVersionAggregate.ValueObjects.LotroNotationVersion", "LotroNotationVersion", b1 =>
                        {
                            b1.Property<Guid>("GameVersionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)")
                                .HasColumnName("LotroNotationVersion");

                            b1.HasKey("GameVersionId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("GameVersions", "translation");

                            b1.WithOwner()
                                .HasForeignKey("GameVersionId");
                        });

                    b.Navigation("LotroNotationVersion")
                        .IsRequired();
                });

            modelBuilder.Entity("LotroKoniecDev.TranslationSystem.Domain.Aggregates.TranslationAggregate.Entities.Translation", b =>
                {
                    b.HasOne("LotroKoniecDev.TranslationSystem.Domain.Aggregates.TranslatorAggregate.Entities.Translator", null)
                        .WithMany()
                        .HasForeignKey("ApprovedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LotroKoniecDev.TranslationSystem.Domain.Aggregates.TranslatorAggregate.Entities.Translator", null)
                        .WithMany()
                        .HasForeignKey("SubmittedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("LotroKoniecDev.TranslationSystem.Domain.Aggregates.TranslationAggregate.ValueObjects.FragmentKey", "FragmentKey", b1 =>
                        {
                            b1.Property<Guid>("TranslationId")
                                .HasColumnType("uuid");

                            b1.Property<int>("FileId")
                                .HasColumnType("integer")
                                .HasColumnName("FileId");

                            b1.Property<long>("GossipId")
                                .HasColumnType("bigint")
                                .HasColumnName("GossipId");

                            b1.HasKey("TranslationId");

                            b1.HasIndex("FileId", "GossipId")
                                .IsUnique();

                            b1.ToTable("Translations", "translation");

                            b1.WithOwner()
                                .HasForeignKey("TranslationId");
                        });

                    b.OwnsOne("LotroKoniecDev.TranslationSystem.Domain.Aggregates.TranslationAggregate.ValueObjects.TranslationSource", "Source", b1 =>
                        {
                            b1.Property<Guid>("TranslationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ArgsId")
                                .HasColumnType("text")
                                .HasColumnName("ArgsId");

                            b1.Property<string>("ArgsOrder")
                                .HasColumnType("text")
                                .HasColumnName("ArgsOrder");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("SourceText");

                            b1.HasKey("TranslationId");

                            b1.HasIndex("Text");

                            NpgsqlIndexBuilderExtensions.HasMethod(b1.HasIndex("Text"), "gin");
                            NpgsqlIndexBuilderExtensions.HasOperators(b1.HasIndex("Text"), new[] { "gin_trgm_ops" });

                            b1.ToTable("Translations", "translation");

                            b1.WithOwner()
                                .HasForeignKey("TranslationId");
                        });

                    b.Navigation("FragmentKey")
                        .IsRequired();

                    b.Navigation("Source")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
